### ISSUE TITLE
アカウント作成

### ISSUE THREAD

**Issue by Murasya** [Murasya/team14#11]
firebaseのアカウントを作成する[アカウント](https://console.firebase.google.com/)

**Comment by Yuki992411** [comment]
プロジェクトを作成しました [team14-memo-app](https://console.firebase.google.com/project/team14-memo-app/firestore)

@Murasya 
このissueは，上のリンクを確認してもらって，問題なければPRなしでそのままissueをクローズしようと思いますが，どうですか？
